### ISSUE TITLE
이미지 색칠 -> 이미지 선택 하면 오류 발생

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#149]
Logcat
```
D/mapName: gangwondoGoseong
D/AllIMGS: androidx.appcompat.widget.AppCompatImageView{9a1d240 V.ED..... ........ 696,155-803,306 #7f090293 app:id/gangwondoGoseong}
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13303 (com.hsu.mapapp), pid 13303 (com.hsu.mapapp)
```
![image](https://user-images.githubusercontent.com/67352902/130311837-e55fb1e1-ba04-4df2-8fec-7f4ef4dae760.png)

**Comment by yuseon-Lim** [comment]
![image](https://user-images.githubusercontent.com/67352902/130311889-3edf3d99-31cc-4bc0-bde5-198cf70c7b72.png)
이거 이렇게 해도 오류 나는거 보면 얘때문은 아닌듯 ㅜ

**Comment by yuseon-Lim** [comment]
새로설치한 pixel 4 이미지로 채우기 -> 갤러리 액티비티에서 뒤로가기 버튼 -> 에러.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hsu.mapapp, PID: 4569
    java.lang.RuntimeException: Unable to resume activity {com.hsu.mapapp/com.hsu.mapapp.MainActivity}: kotlin.TypeCastException: null cannot be cast to non-null type android.graphics.drawable.BitmapDrawable
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.graphics.drawable.BitmapDrawable
        at com.hsu.mapapp.map.MapSeoulFragment.onResume(MapSeoulFragment.kt:116)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3048)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3048)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:7964)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

```

MapSeoulFragment.kt:116은
```kotlin
                val bitmap = (imageView.drawable as BitmapDrawable).bitmap
```

**Comment by yuseon-Lim** [comment]
![image](https://user-images.githubusercontent.com/67352902/130312689-e4642097-3dd3-4c3c-9b30-bb0d6d06703c.png)
해결~
