### ISSUE TITLE
findViewWithTag<ImageView>("$region") return null?

### ISSUE THREAD

**Issue by yuseon-Lim** [HSUITContestTeam/map-app#164]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hsu.mapapp, PID: 18022
    java.lang.NullPointerException: Argument must not be null
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:29)
        at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:23)
        at com.bumptech.glide.request.target.ViewTarget.<init>(ViewTarget.java:62)
        at com.bumptech.glide.request.target.ImageViewTarget.<init>(ImageViewTarget.java:25)
        at com.bumptech.glide.request.target.BitmapImageViewTarget.<init>(BitmapImageViewTarget.java:14)
        at com.hsu.mapapp.map.MapSeoulFragment$uploadImageFromStorage$1$1$1.<init>(MapSeoulFragment.kt:108)
        at com.hsu.mapapp.map.MapSeoulFragment$uploadImageFromStorage$1$1.onComplete(MapSeoulFragment.kt:108)
        at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
![image](https://user-images.githubusercontent.com/67352902/130366944-eeff8d15-5467-418c-bac9-89ae313d7adc.png)
모든 지역에 대한 이미지뷰를 추가 해 보았으나 고성, 해남 제외한 지역은 imageView가 null이 반환됨

![image](https://user-images.githubusercontent.com/67352902/130366925-56f74407-e104-4e1e-afc5-118b6e9d0dc9.png)
![image](https://user-images.githubusercontent.com/67352902/130366940-04d86c11-0ef5-4479-8c92-737cd183388c.png)

**Comment by im-shung** [comment]
#165 해결완~
